# Use the PHP 7.4 runtime
runtime: php74

runtime_config:
  document_root: .

# Defaults to "serve index.php" 
entrypoint: serve handler.php

# If your main page is index.php, comment the above entrypoint setting 

handlers:
- url: /backend
  static_dir: backend

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  DB_USER: root
  DB_PASS: rootadminadel
  DB_NAME: db_elakip
  INSTANCE_UNIX_SOCKET: /cloudsql/refined-iridium-373115:asia-southeast2:el-akip2022